import React from 'react';
import { Payment, ScheduledPayment } from '../../types';
import { Icon } from '../Icon';

interface ReportingActionsProps {
    paymentHistory: Payment[];
    missedPayments: ScheduledPayment[];
}

const ReportingActions: React.FC<ReportingActionsProps> = ({ paymentHistory, missedPayments }) => {
    
    const handleDownloadCsv = () => {
        const headers = ["Date", "Debtor Name", "Account #", "Portfolio", "Amount", "Method", "Type", "Confirmation #"];
        const rows = paymentHistory.map(p => [
            new Date(p.paymentDate).toISOString().split('T')[0],
            `"${p.debtorName}"`,
            p.accountNumber,
            `"${p.portfolioName}"`,
            p.paymentAmount,
            p.paymentMethod,
            p.paymentType,
            p.confirmationNumber
        ].join(','));
        
        const csvContent = [headers.join(','), ...rows].join('\n');
        const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
        const link = document.createElement("a");
        const url = URL.createObjectURL(blob);
        link.setAttribute("href", url);
        link.setAttribute("download", `payment_history_${new Date().toISOString().split('T')[0]}.csv`);
        link.style.visibility = 'hidden';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    const handleGeneratePdf = () => {
        const reportHtml = `
            <html>
                <head>
                    <title>Missed Payments Report</title>
                    <style>
                        body { font-family: sans-serif; margin: 2rem; }
                        h1 { color: #1E293B; border-bottom: 2px solid #E2E8F0; padding-bottom: 0.5rem; }
                        table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
                        th, td { border: 1px solid #CBD5E1; padding: 0.75rem; text-align: left; }
                        th { background-color: #F1F5F9; }
                        tr:nth-child(even) { background-color: #F8FAFC; }
                        .footer { margin-top: 2rem; font-size: 0.8rem; color: #64748B; text-align: center; }
                    </style>
                </head>
                <body>
                    <h1>Missed Payments Report</h1>
                    <p>Generated on: ${new Date().toLocaleDateString()}</p>
                    <table>
                        <thead>
                            <tr>
                                <th>Scheduled Date</th>
                                <th>Debtor Name</th>
                                <th>Account #</th>
                                <th>Amount Missed</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${missedPayments.map(p => `
                                <tr>
                                    <td>${new Date(p.scheduledDate).toLocaleDateString()}</td>
                                    <td>${p.debtorName}</td>
                                    <td>${p.accountNumber}</td>
                                    <td>$${p.scheduledAmount.toFixed(2)}</td>
                                </tr>
                            `).join('')}
                        </tbody>
                    </table>
                    <div class="footer">
                        Report generated by Arc AI Platform. Total Missed Payments: ${missedPayments.length}.
                    </div>
                </body>
            </html>
        `;
        const newWindow = window.open();
        newWindow?.document.write(reportHtml);
        newWindow?.document.close();
        setTimeout(() => {
            newWindow?.print();
            newWindow?.close();
        }, 500);
    };

    return (
        <div className="p-4 bg-slate-100 dark:bg-slate-800/50 rounded-lg border border-slate-200 dark:border-slate-700/50 flex items-center justify-end gap-4">
            <button
                onClick={handleDownloadCsv}
                className="flex items-center gap-2 bg-white dark:bg-slate-700 text-slate-800 dark:text-white font-semibold py-2 px-4 rounded-lg hover:bg-slate-200 dark:hover:bg-slate-600 transition-colors border border-slate-300 dark:border-slate-600"
            >
                <Icon name="download" className="h-5 w-5" />
                Download Payment History (CSV)
            </button>
            <button
                onClick={handleGeneratePdf}
                className="flex items-center gap-2 bg-white dark:bg-slate-700 text-slate-800 dark:text-white font-semibold py-2 px-4 rounded-lg hover:bg-slate-200 dark:hover:bg-slate-600 transition-colors border border-slate-300 dark:border-slate-600"
            >
                <Icon name="download" className="h-5 w-5" />
                Generate Missed Payments Report (PDF)
            </button>
        </div>
    );
};

export default ReportingActions;
